name: Generate Profile Cards

on:
  schedule:
  # - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  generate-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Generate Profile Details Card
        run: |
          curl -o public/profile-details.svg "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=nurazon59&theme=2077&count_private=true"

      - name: Generate Top Languages Card
        run: |
          curl -o public/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=nurazon59&layout=compact&theme=tokyonight&count_private=true"

      - name: Generate GitHub Stats Card
        run: |
          curl -o public/github-stats.svg "https://github-readme-stats.vercel.app/api?username=nurazon59&theme=tokyonight&count_private=true"

      - name: Generate Trophy Card
        run: |
          curl -o public/trophy.svg "https://github-profile-trophy.vercel.app/?username=nurazon59&theme=onedark&count_private=true"

      - uses: stefanzweifel/git-auto-commit-action@v5
